### ISSUE TITLE
Test Cases/solution/05_executeTestClosuresMultiThreadsLayoutManaged FAILED. Reason: java.lang.IllegalArgumentException: TestClosure requires the 1st Closure parameter to be class org.openqa.selenium.chrome.ChromeDriver type

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/TestClosure#7]
with `version = '0.22.1-SNAPSHOT'`
when I executed `Test Suites/solution/05_executeTestClosuresMultiThreadsLayoutManaged`, I got the following error

```
2023-11-15 18:18:01.036 INFO  c.k.katalon.core.main.TestSuiteExecutor  - START Test Suites/solution/05_executeTestClosuresMultiThreadsLayoutManaged
2023-11-15 18:18:01.061 INFO  c.k.katalon.core.main.TestSuiteExecutor  - hostName = kazuakiurayama - kazuakinoair.airport
2023-11-15 18:18:01.061 INFO  c.k.katalon.core.main.TestSuiteExecutor  - os = Mac OS X 64bit
2023-11-15 18:18:01.061 INFO  c.k.katalon.core.main.TestSuiteExecutor  - hostAddress = 192.168.0.27
2023-11-15 18:18:01.061 INFO  c.k.katalon.core.main.TestSuiteExecutor  - katalonVersion = 9.0.0.212
2023-11-15 18:18:01.116 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2023-11-15 18:18:01.117 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/solution/05_executeTestClosuresMultiThreadsLayoutManaged
2023-11-15 18:18:01.297 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/solution/05_executeTestClosuresMultiThreadsLayoutManaged FAILED.
Reason:
java.lang.IllegalArgumentException: TestClosure requires the 1st Closure parameter to be class org.openqa.selenium.chrome.ChromeDriver type
	at com.kazurayam.ks.testclosure.TestClosure.validateClosureParameters(TestClosure.groovy:69)
	at com.kazurayam.ks.testclosure.TestClosure.<init>(TestClosure.groovy:30)
	at 05_executeTestClosuresMultiThreadsLayoutManaged.run(05_executeTestClosuresMultiThreadsLayoutManaged:18)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:187)
	at TempTestSuite1700039879743.run(TempTestSuite1700039879743.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2023-11-15 18:18:01.301 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/solution/05_executeTestClosuresMultiThreadsLayoutManaged FAILED.
Reason:
java.lang.IllegalArgumentException: TestClosure requires the 1st Closure parameter to be class org.openqa.selenium.chrome.ChromeDriver type
	at com.kazurayam.ks.testclosure.TestClosure.validateClosureParameters(TestClosure.groovy:69)
	at com.kazurayam.ks.testclosure.TestClosure.<init>(TestClosure.groovy:30)
	at 05_executeTestClosuresMultiThreadsLayoutManaged.run(05_executeTestClosuresMultiThreadsLayoutManaged:18)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:187)
	at TempTestSuite1700039879743.run(TempTestSuite1700039879743.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2023-11-15 18:18:01.303 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/solution/05_executeTestClosuresMultiThreadsLayoutManaged
2023-11-15 18:18:01.360 INFO  com.kms.katalon.core.util.KeywordUtil    - Start generating HTML report folder at: /Users/kazuakiurayama/katalon-workspace/TestClosure/Reports/20231115_181758/solution/05_executeTestClosuresMultiThreadsLayoutManaged/20231115_181759...
2023-11-15 18:18:01.376 INFO  com.kms.katalon.core.util.KeywordUtil    - HTML report generated
2023-11-15 18:18:01.376 INFO  com.kms.katalon.core.util.KeywordUtil    - Start generating CSV report folder at: /Users/kazuakiurayama/katalon-workspace/TestClosure/Reports/20231115_181758/solution/05_executeTestClosuresMultiThreadsLayoutManaged/20231115_181759...
2023-11-15 18:18:01.381 INFO  com.kms.katalon.core.util.KeywordUtil    - CSV report generated
2023-11-15 18:18:01.401 INFO  c.k.katalon.core.main.TestSuiteExecutor  - --------------------
2023-11-15 18:18:01.401 INFO  c.k.katalon.core.main.TestSuiteExecutor  - END Test Suites/solution/05_executeTestClosuresMultiThreadsLayoutManaged
2023-11-15 18:18:01.401 INFO  c.k.katalon.core.main.TestSuiteExecutor  - ====================

```

**Comment by kazurayam** [comment]
I realized my fault.

I used `org.openqa.selenium.WebDriver` and `org.openqa.selenium.chrome.ChromeDriver` carelessly intermized.

I changed by codes to declare and use ChromeDriver only.
